// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Data.Migrations
{
    [DbContext(typeof(EFCore2FeaturesContext))]
    [Migration("20180124050216_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Domain.Cliente", b =>
                {
                    b.OwnsOne("Domain.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("ClienteId");

                            b1.Property<DateTime>("DataEmissao")
                                .HasColumnName("CPFDataEmissao");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnName("CPF")
                                .HasColumnType("varchar(11)");

                            b1.ToTable("Clientes");

                            b1.HasOne("Domain.Cliente")
                                .WithOne("CPF")
                                .HasForeignKey("Domain.CPF", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Domain.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ClienteId");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasColumnType("varchar(150)");

                            b1.ToTable("Clientes");

                            b1.HasOne("Domain.Cliente")
                                .WithOne("Email")
                                .HasForeignKey("Domain.Email", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
